name: 'Deploy Next.js'
description: 'Deploy Next.js on any Server via SSH'
inputs:
  NEXT_ENV:
    description: 'Next environment: local, development, staging or production (default)'
    required: false
    default: 'production'
  SERVER:
    description: 'SSH target (user@host -p port)'
    required: true
  NEXT_PATH:
    description: 'Path on the remote server where Next.js is located (default: /var/www/next)'
    required: false
    default: '/var/www/next'

runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: |
          next/package-lock.json

    - name: Install node dependencies
      shell: bash
      run: npm --prefix next ci

    - name: Download environment file from remote server
      shell: bash
      run: |
        SHARED_DIR="$(dirname '${{ inputs.NEXT_PATH }}')/shared"

        if ssh ${{ inputs.SERVER }} "test -f '$SHARED_DIR/.env'"; then
          rsync -az ${{ inputs.SERVER }}:"$SHARED_DIR/.env" next/.env
        else
          cp next/.env.example next/.env
        fi

    - name: Build Next
      shell: bash
      run: |
        NODE_ENV=production \
        npm --prefix next run build

    - name: Save built artifacts
      uses: actions/upload-artifact@v7
      with:
        name: next-build
        if-no-files-found: error
        include-hidden-files: true
        path: |
          ./next/.next
          ./next/out
          ./next/public
          ./next/package.json
          ./next/package-lock.json
          ./next/next.config.ts
          ./wordpress/theme/lib/editor
          ./wordpress/package.json
          ./wordpress/package-lock.json