name: 'Deploy WP Theme'
inputs:
  SSH_PRIVATE_KEY:
    description: 'Private key of the SSH user to deploy'
    required: true
  REMOTE_USER:
    description: 'Remote server SSH user'
    required: true
  REMOTE_HOST:
    description: 'Remote server SSH Host (IP adress)'
    required: true
  REMOTE_PORT:
    description: 'Remote server SSH Port (default: 22)'
    required: false
    default: 22
  REMOTE_TARGET:
    description: 'Path on the remote server. (default: /var/www/html)'
    required: false
    default: '/var/www/html'
  WORDPRESS_THEME_NAME:
    description: 'WordPress Theme name'
    required: false
    default: 'superstack'
  RELEASE_BELT_USER:
    description: 'Release Belt User'
    required: false
    default: 'release-belt'
  RELEASE_BELT_PWD:
    description: 'Release Belt Password'
    required: false
  COMPOSER_GITHUB_TOKEN:
    description: 'Composer GitHub Token'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: wp-assets
        path: wordpress/

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ inputs.SSH_PRIVATE_KEY }}
        ARGS: '-raltzv --delete'
        REMOTE_USER: ${{ inputs.REMOTE_USER }}
        REMOTE_HOST: ${{ inputs.REMOTE_HOST }}
        REMOTE_PORT: ${{ inputs.REMOTE_PORT }}
        SOURCE: './wordpress'
        TARGET: '${{ inputs.REMOTE_TARGET }}'
        EXCLUDE: '.github, .gitignore, composer.json, composer.lock, node_modules, packages.json, webpack.config.js, package-lock.json'

    - id: ssh
      uses: kuuak/ssh-action@main
      with:
        SSH_USER: ${{ inputs.REMOTE_USER }}
        SSH_HOST: ${{ inputs.REMOTE_HOST }}
        SSH_PORT: ${{ inputs.REMOTE_PORT }}
        SSH_KEY: ${{ inputs.SSH_PRIVATE_KEY }}

    - name: Start
      shell: bash
      run: |
        ssh ${{ steps.ssh.outputs.SERVER }} \
        "cd ${{ inputs.REMOTE_TARGET }}/wordpress; \
        composer install --no-dev; \
        docker compose down -v; \
        npm run start;"
      env:
        THEME_NAME: ${{ inputs.WORDPRESS_THEME_NAME }}
        RELEASE_BELT_USER: ${{ inputs.RELEASE_BELT_USER }}
        RELEASE_BELT_PWD: ${{ inputs.RELEASE_BELT_PWD }}
        COMPOSER_GITHUB_TOKEN: ${{ inputs.COMPOSER_GITHUB_TOKEN }}
