#!/bin/sh

# Change to the wordpress directory (parent of this script's location)
cd "$(dirname "$0")/.." || exit

# Load per-instance overrides (generated by scripts/setup-instance.sh)
if [ -f ./.env ]; then
	set -a
	. ./.env
	set +a
fi

COMPOSE="docker compose"
THEME_NAME=${THEME_NAME:="superstack"}
PROJECT_CODE=${PROJECT_CODE:="spck"}

echo ""
echo "=====================   STARTING WORDPRESS   ====================="
echo ""
sleep 0.5
THEME_NAME=${THEME_NAME} PROJECT_CODE=${PROJECT_CODE} $COMPOSE -f docker-compose.yml up "$@" --build -d --quiet-pull

echo ""
echo "=============   INSTALLING COMPOSER DEPENDENCIES   ==============="
echo ""
sleep 0.5
$COMPOSE exec wp composer install

echo ""
echo "===================   PROVISIONING WORDPRESS   ==================="
echo ""
sleep 0.5
$COMPOSE exec -T \
    -e WORDPRESS_THEME_NAME="$THEME_NAME" \
    -e WORDPRESS_PATH="/var/www/html" \
    -e WORDPRESS_ENV="dev" \
wp bash < ./scripts/provision.sh
