import type { Metadata, Viewport } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { getLocales } from '@/i18n/get-locales';

import '@/css/base/index.css';

// Fonts
const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

// Metas
export const viewport: Viewport = {
	themeColor: '#ffffff',
	initialScale: 1,
	width: 'device-width',
};

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const revalidate = 3600;

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const { defaultLocale } = await getLocales();

	return (
		<html
			lang={defaultLocale}
			className={`${geistSans.variable} ${geistMono.variable}`}
		>
			<head>
				<link rel="stylesheet" href="/css/theme-generated.css" />
			</head>
			<body>{children}</body>
		</html>
	);
}
