#!/bin/sh

# Generates per-instance env files so several checkouts of this repo
# (e.g. git worktrees) can run WordPress + Next.js side by side
# without port / database / container-name conflicts.
#
# Usage: sh scripts/setup-instance.sh <instance-number 1-9>
#
# Instance N gets:
#   WordPress  http://localhost:808N   (docker project spck-wtN, own MariaDB)
#   MariaDB    localhost:3306N
#   Next.js    http://localhost:310N

set -e
cd "$(dirname "$0")/.." || exit 1

N=${1:?"usage: sh scripts/setup-instance.sh <instance-number 1-9>"}
case "$N" in
	[1-9]) ;;
	*) echo "ERROR: instance number must be a single digit 1-9" >&2; exit 1 ;;
esac

find_free_port() {
	p=$1
	while is_port_taken "$p"; do
		p=$((p + 1))
	done
	echo "$p"
}

# A sibling instance that is configured but not currently running holds no
# listening socket, so lsof alone would hand its port out a second time —
# instances are normally set up first and booted later. Treat every port
# already written to a sibling .env as taken too.
CLAIMED=$(
	for f in "$(dirname "$(pwd)")"/*/wordpress/.env; do
		[ -f "$f" ] || continue
		[ "$f" = "$(pwd)/wordpress/.env" ] && continue
		sed -n -e 's/^WP_PORT=//p' -e 's/^DB_PORT=//p' -e 's/^NEXT_URL=.*:\([0-9][0-9]*\)$/\1/p' "$f"
	done
)

is_port_taken() {
	printf '%s\n' "$CLAIMED" | grep -qx "$1" && return 0
	lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1
}

# Walking up from a busy port pushes this instance onto the slot the next one
# would have used, which then walks up in turn. Report it so the ports in use
# are never a surprise — the generated .env is the source of truth.
warn_if_shifted() {
	[ "$1" = "$2" ] || echo "NOTE: $3 port $2 is busy — using $1 instead." >&2
}

WP_PORT=$(find_free_port $((8080 + N)))
DB_PORT=$(find_free_port $((33060 + N)))
NEXT_PORT=$(find_free_port $((3100 + N)))
warn_if_shifted "$WP_PORT" $((8080 + N)) WordPress
warn_if_shifted "$DB_PORT" $((33060 + N)) MariaDB
warn_if_shifted "$NEXT_PORT" $((3100 + N)) Next.js
PROJECT_CODE="spck-wt$N"
SECRET=$(openssl rand -hex 16)

cat > wordpress/.env <<EOF
PROJECT_CODE=$PROJECT_CODE
THEME_NAME=superstack
WP_PORT=$WP_PORT
DB_PORT=$DB_PORT
WORDPRESS_URL=http://localhost:$WP_PORT
NEXT_URL=http://localhost:$NEXT_PORT
DEV_AUTOLOGIN_SECRET=$SECRET
EOF

cat > wordpress/wp-cli.local.yml <<EOF
# Generated by scripts/setup-instance.sh — do not commit
@local:
  ssh: 'docker:${PROJECT_CODE}_wp/var/www/html'
EOF

cat > next/.env <<EOF
# Generated by scripts/setup-instance.sh — do not commit
WORDPRESS_URL=http://localhost:$WP_PORT
NEXT_URL=http://localhost:$NEXT_PORT
REVALIDATE_SECRET=supersecret
EOF

echo "Instance $N configured in $(pwd)"
echo "  WordPress  : http://localhost:$WP_PORT  (docker project: $PROJECT_CODE)"
echo "  Next.js    : http://localhost:$NEXT_PORT"
echo "  Auto-login : http://localhost:$WP_PORT/?dev_autologin=$SECRET"
echo ""
echo "Next steps:"
echo "  (cd wordpress && npm run build)                        # build the theme assets"
echo "  (cd wordpress && npm start)                            # WordPress on :$WP_PORT"
echo "  sh wordpress/scripts/db-seed.sh /path/to/main-checkout # copy DB + uploads"
echo "  (cd next && npm run dev -- -p $NEXT_PORT)              # Next.js on :$NEXT_PORT"
