#!/bin/sh

# Generates per-instance env files so several checkouts of this repo
# (e.g. git worktrees) can run WordPress + Next.js side by side
# without port / database / container-name conflicts.
#
# Usage: sh scripts/setup-instance.sh <instance-number 1-9>

set -e
cd "$(dirname "$0")/.." || exit 1

N=${1:?"usage: sh scripts/setup-instance.sh <instance-number 1-9>"}
case "$N" in
	[1-9]) ;;
	*) echo "ERROR: instance number must be a single digit 1-9" >&2; exit 1 ;;
esac

command -v lsof >/dev/null 2>&1 ||
	{ echo "ERROR: lsof is required to detect busy ports." >&2; exit 1; }

# Ports are derived from the instance number rather than searched for, so
# instance N is always on 808N/3306N/310N no matter what order instances are
# created or booted in. Refuse the number rather than silently shifting onto
# the slot another instance expects.
WP_PORT=$((8080 + N))
DB_PORT=$((33060 + N))
NEXT_PORT=$((3100 + N))
for p in $WP_PORT $DB_PORT $NEXT_PORT; do
	if lsof -nP -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
		echo "ERROR: port $p is already in use — try a different instance number." >&2
		exit 1
	fi
done

[ -f wordpress/.env ] && echo "NOTE: replacing the existing instance config in $(pwd)" >&2

PROJECT_CODE="spck-wt$N"
SECRET=$(openssl rand -hex 16)

cat > wordpress/.env <<EOF
PROJECT_CODE=$PROJECT_CODE
THEME_NAME=superstack
WP_PORT=$WP_PORT
DB_PORT=$DB_PORT
WORDPRESS_URL=http://localhost:$WP_PORT
NEXT_URL=http://localhost:$NEXT_PORT
DEV_AUTOLOGIN_SECRET=$SECRET
EOF

cat > wordpress/wp-cli.local.yml <<EOF
# Generated by scripts/setup-instance.sh — do not commit
@local:
  ssh: 'docker:${PROJECT_CODE}_wp/var/www/html'
EOF

cat > next/.env <<EOF
# Generated by scripts/setup-instance.sh — do not commit
WORDPRESS_URL=http://localhost:$WP_PORT
NEXT_URL=http://localhost:$NEXT_PORT
REVALIDATE_SECRET=$(openssl rand -hex 16)
EOF

echo "Instance $N configured in $(pwd)"
echo "  WordPress  : http://localhost:$WP_PORT  (docker project: $PROJECT_CODE)"
echo "  Next.js    : http://localhost:$NEXT_PORT"
echo "  Auto-login : http://localhost:$WP_PORT/?dev_autologin=$SECRET  (admin credential — keep it out of shared logs)"
echo ""
echo "Next steps:"
echo "  (cd wordpress && npm run build)                        # build the theme assets"
echo "  (cd wordpress && npm start)                            # WordPress on :$WP_PORT"
echo "  sh wordpress/scripts/db-seed.sh /path/to/source-checkout # copy DB + uploads"
echo "  (cd next && npm run dev -- -p $NEXT_PORT)              # Next.js on :$NEXT_PORT"
