name: 'Build Frontend'
runs:
  using: 'composite'
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node dependencies
      shell: bash
      run: npm install --frozen-lockfile --legacy-peer-deps

    - name: Frontend ESLint
      shell: bash
      run: npm run lint --verbose

    - name: Frontend Typescript Build
      shell: bash
      run: npm run build:typescript -- --verbose
