name: Deploy WordPress - theme and plugins
on:
  # Allows to be called by another workflow
  workflow_call:
    secrets:
      SSH_USER:
        required: true
        description: 'SSH user.'
      SSH_HOST:
        required: true
        description: 'SSH Host. (IP adress)'
      SSH_PORT:
        description: 'SSH Port.'
        required: true
      SSH_PRIVATE_KEY:
        required: true
        description: 'Private key of the SSH user to deploy.'
      NEXT_URL:
        required: true
        description: 'Next URL.'
      WORDPRESS_PATH:
        required: true
        description: 'WordPress absolute path on remote server.'
      WORDPRESS_THEME_NAME:
        description: 'WordPress folder theme name.'
        required: true

jobs:
  theme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-theme
      - uses: ./.github/actions/deploy-theme
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          WORDPRESS_THEME_NAME: ${{ vars.WORDPRESS_THEME_NAME }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_TARGET: ${{ secrets.WORDPRESS_PATH }}

  provision:
    runs-on: ubuntu-latest
    needs: [theme]
    steps:
      - uses: actions/checkout@v4

      - name: deploy composer
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-raultzv --delete'
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          SOURCE: './wordpress/composer.json ./wordpress/composer.lock'
          TARGET: ${{ secrets.WORDPRESS_PATH }}

      - id: ssh
        uses: kuuak/ssh-action@main
        with:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Require composer depedencies
        shell: bash
        run: ssh ${{ steps.ssh.outputs.SERVER }} "cd ${{ secrets.WORDPRESS_PATH }}; composer install --no-dev"

      - name: Execute provisiton script
        shell: bash
        run: |
          ssh ${{ steps.ssh.outputs.SERVER }} \
            "cd ${{ secrets.WORDPRESS_PATH }}; \
            env THEME_NAME=${{ vars.WORDPRESS_THEME_NAME }} \
            NEXT_URL=${{ secrets.NEXT_URL }} \
            WORDPRESS_PATH=${{ secrets.WORDPRESS_PATH }} \
            /bin/bash -s " < ./wordpress/scripts/provision.sh
