name: Build and test develop branch
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - 'develop'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Quickly run a test procedure to validate the code being pushed.
  # This is the first step of the testing procedure in the CI pipeline.
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check github environment secrets and variables
        run: |
          echo "Checking secrets and variables for '${{ matrix.environment }}.' environment..."
          missing_vars=0
          for var in COMPOSER_GITHUB_TOKEN WORDPRESS_THEME_NAME RELEASE_BELT_USER RELEASE_BELT_PWD; do
            if [ -z "${!var}" ]; then
              echo "$var is not set."
              missing_vars=$((missing_vars+1))
            else
              echo "$var is set to '${!var}'."
            fi
          done

          if [ $missing_vars -ne 0 ]; then
            echo "inputs_checked=false" >> $GITHUB_OUTPUT
            echo "Error: $missing_vars variables are missing."
            exit 1
          else
            echo "inputs_checked=true" >> $GITHUB_OUTPUT
          fi
        env:
          WORDPRESS_THEME_NAME: ${{ vars.WORDPRESS_THEME_NAME }}
          RELEASE_BELT_USER: ${{ vars.RELEASE_BELT_USER }}
          RELEASE_BELT_PWD: ${{ secrets.RELEASE_BELT_PWD }}
          COMPOSER_GITHUB_TOKEN: ${{ secrets.COMPOSER_GITHUB_TOKEN }}

      - name: Build Theme
        uses: ./.github/actions/build-theme

      - name: Build Frontend
        uses: ./.github/actions/build-frontend

      - name: Unit Tests for React Components
        shell: bash
        run: npm run test:components
